[project]
name = "eol-laptop-reminders"
version = "0.1.0"
description = "Read the readme file"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pywin32>=311",
]

[dependency-groups]
dev = [
    "ruff>=0.14.0",
]
